# Generated by Django 3.2.9 on 2021-11-10 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0002_auto_20211109_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commentDislikes',
            new_name='comment_dislikes',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commentLikes',
            new_name='comment_likes',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='songId',
            new_name='video_id',
        ),
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_reply', models.CharField(max_length=400)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Comments.comment')),
            ],
        ),
    ]
