# Generated by Django 3.2.9 on 2021-11-10 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0003_auto_20211110_1049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentReply',
        ),
    ]
